//! Desktop setup orchestration. No setup work enters the routing decision path.
use serde_json::{Value, json};
use std::{
    collections::BTreeSet,
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    path::{Path, PathBuf},
    process::Stdio,
    time::{Duration, SystemTime, UNIX_EPOCH},
};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWriteExt};
use uuid::Uuid;

const LIMIT: u64 = 1024 * 1024;
const API: &str = "https://api.openai.com/v1";
const APP: &str = "io.github.asdecided.wayfinder";
const SECRET_TOOL: &str = "/usr/bin/secret-tool";
const STARTER: &str = "# Generated by wayfinder-router init (preset: local).\n[routing]\nthreshold = 1.0\n\n[gateway]\noffline = true\n\n[gateway.models.local]\nbase_url = \"http://localhost:11434/v1\"\nmodel = \"llama3.1\"\ncost_per_1k = 0.0\n";
type Result<T> = std::result::Result<T, &'static str>;
const IO_ERROR: &str =
    "Setup could not read or write its state. Existing custom files were preserved.";
const CANCELLED: &str =
    "Operation cancelled or timed out. Recheck setup; repair or disconnect interrupted activation.";

// Match the provider layer's redacted, zero-on-drop credential ownership.
// No Serialize or Clone: secret buffers never enter a result or journal.
struct SecretBytes(Vec<u8>);
impl std::ops::Deref for SecretBytes {
    type Target = Vec<u8>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl std::ops::DerefMut for SecretBytes {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl Drop for SecretBytes {
    fn drop(&mut self) {
        self.0.fill(0);
    }
}
impl std::fmt::Debug for SecretBytes {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("[REDACTED]")
    }
}

fn valid_model(s: &str) -> bool {
    !s.is_empty()
        && s.len() <= 256
        && s.bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"_.:/-".contains(&b))
}
fn valid_item(s: &str) -> bool {
    s.len() == 32
        && s.bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}
fn policy(model: &str, item: &str) -> Result<String> {
    if !valid_model(model) || !valid_item(item) {
        return Err("Invalid model or credential reference.");
    }
    Ok(format!(
        "# Owned by Wayfinder Omarchy guided setup. Hosted routing explicitly selected.\n[[routing.tiers]]\nmin_score = 0.0\nmodel = \"openai\"\n\n[gateway]\noffline = false\n\n[gateway.models.openai]\nprovider = \"openai-compatible\"\nbase_url = \"{API}\"\nmodel = \"{model}\"\napi_key_env = \"WAYFINDER_DESKTOP_OPENAI_{item}\"\napi_key_cmd = \"{SECRET_TOOL} lookup application {APP} credential {item}\"\n"
    ))
}
fn read(path: &Path) -> Result<String> {
    let meta = fs::symlink_metadata(path).map_err(|_| IO_ERROR)?;
    if !meta.is_file() || meta.len() > LIMIT {
        return Err(IO_ERROR);
    }
    let mut text = String::new();
    File::open(path)
        .map_err(|_| IO_ERROR)?
        .take(LIMIT + 1)
        .read_to_string(&mut text)
        .map_err(|_| IO_ERROR)?;
    if text.len() as u64 > LIMIT {
        return Err(IO_ERROR);
    }
    Ok(text)
}
fn atomic(path: &Path, text: &str) -> Result<()> {
    if path.is_symlink() {
        return Err("Refusing to replace a symlink.");
    }
    let parent = path.parent().ok_or(IO_ERROR)?;
    let temporary = parent.join(format!(".setup-{}", Uuid::new_v4()));
    let result = (|| {
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        let mut file = options.open(&temporary).map_err(|_| IO_ERROR)?;
        file.write_all(text.as_bytes()).map_err(|_| IO_ERROR)?;
        file.sync_all().map_err(|_| IO_ERROR)?;
        fs::rename(&temporary, path).map_err(|_| IO_ERROR)?;
        File::open(parent)
            .and_then(|f| f.sync_all())
            .map_err(|_| IO_ERROR)
    })();
    let _ = fs::remove_file(temporary);
    result
}
async fn bounded(mut stream: impl AsyncRead + Unpin) -> Result<SecretBytes> {
    let mut bytes = SecretBytes(Vec::new());
    (&mut stream)
        .take(LIMIT + 1)
        .read_to_end(&mut bytes)
        .await
        .map_err(|_| "Operation output could not be read.")?;
    if bytes.len() as u64 > LIMIT {
        return Err("Operation returned too much data.");
    }
    Ok(bytes)
}
#[cfg(unix)]
struct ProcessGroup(Option<rustix::process::Pid>);
#[cfg(unix)]
impl Drop for ProcessGroup {
    fn drop(&mut self) {
        if let Some(pid) = self.0 {
            let _ = rustix::process::kill_process_group(pid, rustix::process::Signal::KILL);
        }
    }
}
async fn child(program: &Path, args: &[&str], input: &[u8]) -> Result<SecretBytes> {
    let mut command = tokio::process::Command::new(program);
    command
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .kill_on_drop(true);
    #[cfg(unix)]
    command.process_group(0);
    let mut process = command
        .spawn()
        .map_err(|_| "Required program could not start. Check the installation.")?;
    #[cfg(unix)]
    let _group = ProcessGroup(
        process
            .id()
            .and_then(|id| rustix::process::Pid::from_raw(id as i32)),
    );
    let mut stdin = process.stdin.take().ok_or(IO_ERROR)?;
    let stdout = process.stdout.take().ok_or(IO_ERROR)?;
    tokio::time::timeout(Duration::from_secs(20), async {
        let write = async {
            stdin.write_all(input).await.map_err(|_| IO_ERROR)?;
            drop(stdin);
            Ok::<_, &'static str>(())
        };
        let ((), output, status) = tokio::try_join!(write, bounded(stdout), async {
            process.wait().await.map_err(|_| IO_ERROR)
        })?;
        if !status.success() {
            return Err(
                "Operation failed. Check service status or unlock the desktop keyring, then retry.",
            );
        }
        Ok(output)
    })
    .await
    .map_err(|_| "Operation timed out. Unlock the desktop keyring and retry.")?
}
async fn request(
    client: &reqwest::Client,
    url: &str,
    key: Option<&str>,
    body: Option<Value>,
) -> Result<Value> {
    let mut request = if let Some(body) = body {
        client.post(url).json(&body)
    } else {
        client.get(url)
    };
    if let Some(key) = key {
        request = request.bearer_auth(key);
    }
    let mut response = request
        .send()
        .await
        .map_err(|_| "Could not reach the provider or Router. Check the connection and retry.")?;
    if !response.status().is_success() {
        return Err(match response.status().as_u16() {
            401 => "API key rejected. Replace it and try again.",
            403 => "This key does not have permission for this model.",
            404 => "Model unavailable. Refresh models and choose again.",
            429 => "Rate or quota limit reached. Check API billing and retry.",
            400 => "This model did not accept the chat test. Choose a compatible chat model.",
            _ => "Request failed. Check provider availability and retry.",
        });
    }
    let receipt = response
        .headers()
        .get("x-wayfinder-router-request-id")
        .and_then(|h| h.to_str().ok())
        .map(str::to_owned);
    let mut bytes = Vec::new();
    while let Some(chunk) = response
        .chunk()
        .await
        .map_err(|_| "Response could not be read.")?
    {
        if bytes.len() + chunk.len() > LIMIT as usize {
            return Err("Response exceeded the setup limit.");
        }
        bytes.extend_from_slice(&chunk);
    }
    let mut value: Value =
        serde_json::from_slice(&bytes).map_err(|_| "Provider returned an invalid response.")?;
    if !value.is_object() {
        return Err("Provider returned an invalid response.");
    }
    if let Some(receipt) = receipt {
        value["_router_request_id"] = json!(receipt);
    }
    Ok(value)
}
fn model_list(value: &Value) -> Result<Value> {
    let models: BTreeSet<&str> = value["data"]
        .as_array()
        .ok_or("No usable model list returned.")?
        .iter()
        .filter_map(|row| row["id"].as_str())
        .filter(|s| valid_model(s))
        .collect();
    if models.is_empty() || models.len() > 2000 {
        return Err("No usable model list returned.");
    }
    Ok(json!(models))
}
struct Setup {
    config: PathBuf,
    directory: PathBuf,
    endpoint: String,
    port: String,
    client: reqwest::Client,
    router: PathBuf,
    secret_tool: PathBuf,
    systemctl: PathBuf,
    provider_url: String,
}
impl Setup {
    fn new(config: PathBuf, endpoint: String, default: &Path) -> Result<Self> {
        if config != default
            || !config.is_absolute()
            || fs::canonicalize(&config).map_err(|_| IO_ERROR)? != config
        {
            return Err(
                "Guided setup preserves custom policy paths. Use the configuration guide for this policy.",
            );
        }
        let port = endpoint
            .strip_prefix("http://127.0.0.1:")
            .filter(|s| !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit()))
            .and_then(|s| s.parse::<u16>().ok())
            .filter(|p| *p > 0)
            .ok_or("Guided setup requires a 127.0.0.1 HTTP endpoint with a valid port.")?
            .to_string();
        let directory = config.parent().ok_or(IO_ERROR)?.join("omarchy-setup");
        if directory.is_symlink() {
            return Err("Setup directory must not be a symlink.");
        }
        let mut builder = fs::DirBuilder::new();
        #[cfg(unix)]
        {
            use std::os::unix::fs::DirBuilderExt;
            builder.mode(0o700);
        }
        if !directory.exists() {
            builder.create(&directory).map_err(|_| IO_ERROR)?;
        }
        let client = reqwest::Client::builder()
            .no_proxy()
            .redirect(reqwest::redirect::Policy::none())
            .timeout(Duration::from_secs(25))
            .build()
            .map_err(|_| IO_ERROR)?;
        Ok(Self {
            config,
            directory,
            endpoint,
            port,
            client,
            router: std::env::current_exe().map_err(|_| IO_ERROR)?,
            secret_tool: SECRET_TOOL.into(),
            systemctl: "systemctl".into(),
            provider_url: API.into(),
        })
    }
    fn load(&self) -> Result<Value> {
        let path = self.directory.join("state.json");
        if !path.exists() && !path.is_symlink() {
            return Ok(json!({}));
        }
        let state: Value = serde_json::from_str(&read(&path)?).map_err(|_| IO_ERROR)?;
        if state["schema"] != 1 || !state["item"].as_str().is_some_and(valid_item) {
            return Err("Setup state is invalid. Existing configuration was preserved.");
        }
        Ok(state)
    }
    fn save(&self, state: &Value) -> Result<()> {
        atomic(&self.directory.join("state.json"), &state.to_string())
    }
    fn unchanged(&self, state: &Value) -> Result<String> {
        let current = read(&self.config)?;
        if current == STARTER {
            return Ok(current);
        }
        if let (Some(model), Some(item)) = (state["model"].as_str(), state["item"].as_str()) {
            if current == policy(model, item)? {
                return Ok(current);
            }
        }
        Err("This policy has custom changes. Guided setup will not overwrite them.")
    }
    fn status(&self) -> Result<Value> {
        let state = self.load()?;
        self.unchanged(&state)?;
        Ok(
            json!({"ok":true,"schema_version":1,"stage":state["stage"].as_str().unwrap_or("provider"),"model":state["model"].as_str().unwrap_or(""),"models":state.get("models").cloned().unwrap_or(json!([])),"keyringInstalled":self.secret_tool.is_file(),"verifiedAt":state["verifiedAt"],"owned":state.get("item").is_some()}),
        )
    }
    async fn secret(&self, action: &str, item: &str, key: &[u8]) -> Result<SecretBytes> {
        if !valid_item(item) {
            return Err("Invalid credential reference.");
        }
        if !self.secret_tool.is_file() {
            return Err(
                "Install libsecret and a Secret Service keyring, then unlock it and retry. Keys are never saved to a plain-text fallback.",
            );
        }
        let mut args = vec![action];
        if action == "store" {
            args.push("--label=Wayfinder OpenAI");
        }
        if action == "search" {
            args.extend(["--all", "--unlock"]);
        }
        args.extend(["application", APP, "credential", item]);
        child(&self.secret_tool, &args, key).await
    }
    async fn restart(&self) -> Result<()> {
        child(
            &self.router,
            &[
                "service",
                "install",
                "--config",
                self.config.to_str().ok_or(IO_ERROR)?,
                "--host",
                "127.0.0.1",
                "--port",
                &self.port,
            ],
            &[],
        )
        .await?;
        child(
            &self.systemctl,
            &["--user", "restart", "wayfinder-router.service"],
            &[],
        )
        .await?;
        Ok(())
    }
    async fn action(&self, action: &str, model: &str, key: &str) -> Result<Value> {
        let mut state = self.load()?;
        let current = self.unchanged(&state)?;
        match action {
            "status" => {}
            "discover" => {
                if state.get("item").is_some() && state["stage"] != "saving-key" {
                    return Err(
                        "Disconnect the existing setup first to replace its key. Your active setup is preserved.",
                    );
                }
                if key.is_empty()
                    || key.len() > 4096
                    || !key.bytes().all(|b| (33..=126).contains(&b))
                {
                    return Err("Enter a valid API key.");
                }
                let models = model_list(
                    &request(
                        &self.client,
                        &format!("{}/models", self.provider_url),
                        Some(key),
                        None,
                    )
                    .await?,
                )?;
                let item = state["item"]
                    .as_str()
                    .map(str::to_owned)
                    .unwrap_or_else(|| Uuid::new_v4().simple().to_string());
                state = json!({"schema":1,"stage":"saving-key","item":item,"models":models});
                self.save(&state)?;
                self.secret("store", &item, key.as_bytes()).await?;
                state["stage"] = json!("model");
                self.save(&state)?;
            }
            "refresh-models" => {
                let item = state["item"].as_str().ok_or("Connect OpenAI first.")?;
                let mut bytes = self.secret("lookup", item, &[]).await?;
                let result = request(
                    &self.client,
                    &format!("{}/models", self.provider_url),
                    Some(
                        std::str::from_utf8(&bytes)
                            .map_err(|_| "Invalid stored credential.")?
                            .trim(),
                    ),
                    None,
                )
                .await;
                bytes.fill(0);
                state["models"] = model_list(&result?)?;
                state.as_object_mut().ok_or(IO_ERROR)?.remove("verifiedAt");
                self.save(&state)?;
            }
            "activate" => {
                if state["stage"] != "model"
                    || !state["models"]
                        .as_array()
                        .is_some_and(|m| m.contains(&json!(model)))
                {
                    return Err("Save a key and select a discovered model first.");
                }
                let candidate = policy(model, state["item"].as_str().ok_or(IO_ERROR)?)?;
                wayfinder_config::gateway::gateway_config_from_toml(&candidate, "guided setup")
                    .map_err(|_| "The Router rejected the proposed policy.")?;
                wayfinder_config::routing_config_from_toml(
                    &candidate,
                    "guided setup",
                    None,
                    wayfinder_config::TierOrderPolicy::StrictInput,
                )
                .map_err(|_| "The Router rejected the proposed routing policy.")?;
                if read(&self.config)? != current {
                    return Err("Policy changed during setup. No changes made.");
                }
                state["stage"] = json!("activating");
                state["model"] = json!(model);
                self.save(&state)?;
                atomic(&self.config, &candidate)?;
                self.restart().await?;
                state["stage"] = json!("test");
                self.save(&state)?;
            }
            "test" => {
                let selected = state["model"]
                    .as_str()
                    .ok_or("Activate your selected model first.")?
                    .to_owned();
                if current != policy(&selected, state["item"].as_str().ok_or(IO_ERROR)?)? {
                    return Err("Activate your selected model first.");
                }
                state.as_object_mut().ok_or(IO_ERROR)?.remove("verifiedAt");
                state["stage"] = json!("test");
                self.save(&state)?;
                let health = request(
                    &self.client,
                    &format!("{}/healthz", self.endpoint),
                    None,
                    None,
                )
                .await?;
                if health["offline"] != false || health["status"] != "ok" {
                    return Err(
                        "Router not ready for hosted requests. Unlock the keyring and repair the service.",
                    );
                }
                let models = request(
                    &self.client,
                    &format!("{}/router/models", self.endpoint),
                    None,
                    None,
                )
                .await?;
                if models["dry_run"] == true
                    || !models["models"].as_array().is_some_and(|rows| {
                        rows.iter().any(|m| {
                            m["name"] == "openai"
                                && m["model"] == selected
                                && m["endpoint"] == API
                                && m["key_ok"] == true
                        })
                    })
                {
                    return Err(
                        "Running Router has a different model. Repair the service and retry.",
                    );
                }
                let response = request(&self.client, &format!("{}/v1/chat/completions", self.endpoint), Some("wayfinder-local"), Some(json!({"model":"openai","messages":[{"role":"user","content":format!("Reply with the single word connected. Test ID: {}", Uuid::new_v4())}],"max_completion_tokens":256,"stream":false}))).await?;
                if !response["choices"][0]["message"]["content"]
                    .as_str()
                    .is_some_and(|s| !s.trim().is_empty())
                {
                    return Err(
                        "The model returned no text within the test limit. Choose another chat model or retry.",
                    );
                }
                let receipt = response["_router_request_id"]
                    .as_str()
                    .ok_or("Response has no Router receipt. Retry the test.")?;
                let recent = request(
                    &self.client,
                    &format!("{}/router/recent?limit=8", self.endpoint),
                    None,
                    None,
                )
                .await?;
                if !recent["recent"].as_array().is_some_and(|rows| {
                    rows.iter().any(|r| {
                        r["request_id"] == receipt
                            && r["served_by"] == "openai"
                            && r["http_status"] == 200
                            && r["outcome"] == "succeeded"
                    })
                }) {
                    return Err(
                        "A response arrived but its successful Router receipt was not verified. Retry the test.",
                    );
                }
                state["stage"] = json!("verified");
                state["verifiedAt"] = json!(
                    SystemTime::now()
                        .duration_since(UNIX_EPOCH)
                        .map_err(|_| IO_ERROR)?
                        .as_secs()
                );
                self.save(&state)?;
            }
            "repair" => {
                state.as_object_mut().ok_or(IO_ERROR)?.remove("verifiedAt");
                if let Some(model) = state["model"].as_str() {
                    if current == policy(model, state["item"].as_str().ok_or(IO_ERROR)?)? {
                        state["stage"] = json!("test");
                    } else {
                        state["stage"] = json!("model");
                        state.as_object_mut().ok_or(IO_ERROR)?.remove("model");
                    }
                    self.save(&state)?;
                }
                self.restart().await?;
            }
            "disconnect" => {
                if let Some(item) = state["item"].as_str().map(str::to_owned) {
                    child(
                        &self.systemctl,
                        &["--user", "stop", "wayfinder-router.service"],
                        &[],
                    )
                    .await?;
                    state["stage"] = json!("disconnecting");
                    state.as_object_mut().ok_or(IO_ERROR)?.remove("verifiedAt");
                    self.save(&state)?;
                    atomic(&self.config, STARTER)?;
                    let mut found = self.secret("search", &item, &[]).await?;
                    let present = !found.is_empty();
                    found.fill(0);
                    if present {
                        self.secret("clear", &item, &[]).await?;
                    }
                    let mut remaining = self.secret("search", &item, &[]).await?;
                    let present = !remaining.is_empty();
                    remaining.fill(0);
                    if present {
                        return Err(
                            "Credential removal was not confirmed. Unlock the keyring and retry disconnect.",
                        );
                    }
                    fs::remove_file(self.directory.join("state.json")).map_err(|_| IO_ERROR)?;
                    self.restart().await?;
                }
            }
            _ => return Err("Unknown setup action."),
        }
        self.status()
    }
}

pub(crate) fn run_process(arguments: &[std::ffi::OsString], stdout: &mut dyn Write) -> i32 {
    let result = (|| {
        let arguments = arguments
            .iter()
            .map(|s| {
                s.to_str()
                    .map(str::to_owned)
                    .ok_or("Setup arguments must be UTF-8.")
            })
            .collect::<Result<Vec<_>>>()?;
        let runtime = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|_| IO_ERROR)?;
        let result = runtime.block_on(async {
            let operation = tokio::time::timeout(Duration::from_secs(90), execute(&arguments, tokio::io::stdin()));
            #[cfg(unix)] {
                let mut terminate = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate()).map_err(|_| IO_ERROR)?;
                tokio::select! { result = operation => result.map_err(|_| CANCELLED)?, _ = terminate.recv() => Err(CANCELLED) }
            }
            #[cfg(not(unix))] { operation.await.map_err(|_| CANCELLED)? }
        });
        // Stdin uses a blocking worker; cancellation must not wait for an input
        // writer that never closes its pipe. The process exits after this call.
        runtime.shutdown_timeout(Duration::from_millis(100));
        result
    })();
    let (value, code) = match result {
        Ok(value) => (value, 0),
        Err(error) => (json!({"ok":false,"schema_version":1,"error":error}), 1),
    };
    let _ = writeln!(stdout, "{value}");
    code
}
async fn execute(arguments: &[String], stdin: impl AsyncRead + Unpin) -> Result<Value> {
    if arguments == ["--help"] {
        return Ok(
            json!({"ok":true,"schema_version":1,"usage":"wayfinder-router setup ACTION --config PATH --endpoint http://127.0.0.1:PORT [--model MODEL]","actions":["status","discover","refresh-models","activate","test","repair","disconnect"],"credential_input":"discover reads the API key from stdin"}),
        );
    }
    if !cfg!(target_os = "linux") {
        return Err("Guided Secret Service setup is currently supported on Linux.");
    }
    let action = arguments.first().ok_or("Setup action is required.")?;
    let mut config = None;
    let mut endpoint = None;
    let mut model = String::new();
    let mut pairs = arguments[1..].chunks_exact(2);
    for pair in &mut pairs {
        match pair[0].as_str() {
            "--config" if config.is_none() => config = Some(PathBuf::from(&pair[1])),
            "--endpoint" if endpoint.is_none() => endpoint = Some(pair[1].clone()),
            "--model" if model.is_empty() => model = pair[1].clone(),
            _ => return Err("Invalid or duplicate setup option."),
        }
    }
    if !pairs.remainder().is_empty() {
        return Err("Setup option requires a value.");
    }
    let home = std::env::var_os("HOME").ok_or(IO_ERROR)?;
    let default = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(home).join(".config"))
        .join("wayfinder/wayfinder-router.toml");
    let setup = Setup::new(
        config.ok_or("--config is required.")?,
        endpoint.ok_or("--endpoint is required.")?,
        &default,
    )?;
    let _lock = acquire_lock(&setup.directory)?;
    let mut bytes = SecretBytes(Vec::new());
    if action == "discover" {
        use tokio::io::AsyncBufReadExt;
        tokio::io::BufReader::new(stdin.take(4098))
            .read_until(b'\n', &mut bytes)
            .await
            .map_err(|_| "Could not read API key from stdin.")?;
        if bytes.last() == Some(&b'\n') {
            bytes.pop();
        }
    }
    let key = std::str::from_utf8(&bytes).map_err(|_| "Invalid API key input.")?;
    let result = setup.action(action, &model, key).await;
    bytes.fill(0);
    result
}
fn acquire_lock(directory: &Path) -> Result<File> {
    let mut options = OpenOptions::new();
    options.create(true).read(true).write(true).truncate(false);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options
            .mode(0o600)
            .custom_flags(rustix::fs::OFlags::NOFOLLOW.bits() as i32);
    }
    let lock = options.open(directory.join("lock")).map_err(|_| IO_ERROR)?;
    #[cfg(unix)]
    rustix::fs::flock(&lock, rustix::fs::FlockOperation::NonBlockingLockExclusive)
        .map_err(|_| "Another setup operation is running.")?;
    Ok(lock)
}

#[cfg(all(test, target_os = "linux"))]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use std::os::unix::fs::{PermissionsExt, symlink};
    struct Fixture {
        root: PathBuf,
        setup: Setup,
    }
    impl Fixture {
        fn new() -> Self {
            let root = std::env::temp_dir().join(format!("wayfinder-setup-{}", Uuid::new_v4()));
            fs::create_dir_all(&root).unwrap();
            let config = root.join("wayfinder-router.toml");
            fs::write(&config, STARTER).unwrap();
            let mut setup =
                Setup::new(config.clone(), "http://127.0.0.1:8088".into(), &config).unwrap();
            let success = root.join("success");
            executable(&success, "#!/bin/sh\nexit 0\n");
            setup.router = success.clone();
            setup.systemctl = success;
            setup.secret_tool = root.join("secret-tool");
            executable(
                &setup.secret_tool,
                &format!(
                    "#!/bin/sh\ncase \"$1\" in\nstore) cat > '{}' ;;\nlookup) cat '{}' ;;\nsearch) if [ -f '{}' ]; then printf present; fi ;;\nclear) rm -f '{}' ;;\nesac\n",
                    root.join("key").display(),
                    root.join("key").display(),
                    root.join("key").display(),
                    root.join("key").display()
                ),
            );
            Self { root, setup }
        }
        fn state(&self, stage: &str) -> Value {
            json!({"schema":1,"item":"abcdef0123456789abcdef0123456789","stage":stage,"models":["chat-model"]})
        }
    }
    impl Drop for Fixture {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }
    fn executable(path: &Path, source: &str) {
        fs::write(path, source).unwrap();
        fs::set_permissions(path, fs::Permissions::from_mode(0o700)).unwrap();
    }
    async fn server(responses: Vec<String>) -> (String, tokio::task::JoinHandle<Vec<String>>) {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let url = format!("http://{}", listener.local_addr().unwrap());
        let task = tokio::spawn(async move {
            let mut requests = Vec::new();
            for response in responses {
                let (mut stream, _) = listener.accept().await.unwrap();
                let mut buffer = vec![0; 16384];
                let size = stream.read(&mut buffer).await.unwrap();
                requests.push(String::from_utf8_lossy(&buffer[..size]).to_string());
                stream.write_all(response.as_bytes()).await.unwrap();
            }
            requests
        });
        (url, task)
    }
    fn response(body: Value, extra: &str) -> String {
        let body = body.to_string();
        format!(
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n{extra}\r\n{body}",
            body.len()
        )
    }
    #[tokio::test]
    async fn policy_and_state_guards_preserve_custom_files() {
        let f = Fixture::new();
        assert_eq!(f.setup.status().unwrap()["stage"], "provider");
        fs::write(&f.setup.config, "# user policy").unwrap();
        for action in [
            "status",
            "discover",
            "activate",
            "repair",
            "disconnect",
            "test",
        ] {
            assert!(
                f.setup
                    .action(action, "chat-model", "secret")
                    .await
                    .is_err()
            );
            assert_eq!(
                fs::read_to_string(&f.setup.config).unwrap(),
                "# user policy"
            );
        }
        fs::remove_file(&f.setup.config).unwrap();
        symlink(f.root.join("missing"), &f.setup.config).unwrap();
        assert!(f.setup.status().is_err());
    }
    #[tokio::test]
    async fn discovery_stores_key_only_in_secret_service_and_disconnect_is_idempotent() {
        let mut f = Fixture::new();
        let (url, task) = server(vec![response(
            json!({"data":[{"id":"chat-model"},{"id":"bad\"model"},{"id":"chat-model"}]}),
            "",
        )])
        .await;
        f.setup.provider_url = url;
        let result = f.setup.action("discover", "", "test-secret").await.unwrap();
        assert_eq!(result["models"], json!(["chat-model"]));
        assert!(
            !read(&f.setup.directory.join("state.json"))
                .unwrap()
                .contains("test-secret")
        );
        assert!(!read(&f.setup.config).unwrap().contains("test-secret"));
        assert_eq!(read(&f.root.join("key")).unwrap(), "test-secret");
        assert!(task.await.unwrap()[0].contains("Bearer test-secret"));
        let active = f.setup.action("activate", "chat-model", "").await.unwrap();
        assert_eq!(active["stage"], "test");
        assert!(read(&f.setup.config).unwrap().contains("api_key_cmd"));
        assert_eq!(
            f.setup.action("disconnect", "", "").await.unwrap()["stage"],
            "provider"
        );
        assert!(!f.root.join("key").exists());
        assert_eq!(read(&f.setup.config).unwrap(), STARTER);
        assert!(f.setup.action("disconnect", "", "").await.is_ok());
    }
    #[tokio::test]
    async fn failed_credential_store_retains_cleanup_identity() {
        let mut f = Fixture::new();
        executable(&f.setup.secret_tool, "#!/bin/sh\nexit 1\n");
        let (url, task) = server(vec![response(json!({"data":[{"id":"chat-model"}]}), "")]).await;
        f.setup.provider_url = url;
        assert!(f.setup.action("discover", "", "test-secret").await.is_err());
        task.await.unwrap();
        assert_eq!(f.setup.load().unwrap()["stage"], "saving-key");
        assert_eq!(read(&f.setup.config).unwrap(), STARTER);
    }
    #[tokio::test]
    async fn failed_restart_retains_promoted_policy_and_repair_resumes() {
        let f = Fixture::new();
        f.setup.save(&f.state("model")).unwrap();
        executable(&f.setup.router, "#!/bin/sh\nexit 1\n");
        assert!(f.setup.action("activate", "chat-model", "").await.is_err());
        assert_eq!(f.setup.load().unwrap()["stage"], "activating");
        executable(&f.setup.router, "#!/bin/sh\nexit 0\n");
        assert_eq!(
            f.setup.action("repair", "", "").await.unwrap()["stage"],
            "test"
        );
        atomic(&f.setup.config, STARTER).unwrap();
        assert_eq!(
            f.setup.action("repair", "", "").await.unwrap()["stage"],
            "model"
        );
        assert!(f.setup.load().unwrap().get("model").is_none());
    }
    #[tokio::test]
    async fn failed_secret_removal_retains_journal_and_starter() {
        let f = Fixture::new();
        f.setup.save(&f.state("model")).unwrap();
        executable(&f.setup.secret_tool, "#!/bin/sh\nexit 1\n");
        assert!(f.setup.action("disconnect", "", "").await.is_err());
        assert_eq!(f.setup.load().unwrap()["stage"], "disconnecting");
        assert_eq!(read(&f.setup.config).unwrap(), STARTER);
    }
    #[tokio::test]
    async fn request_test_requires_exact_successful_receipt_and_clears_old_proof() {
        for receipt in ["wrong-receipt", "expected-receipt"] {
            let mut f = Fixture::new();
            let mut state = f.state("verified");
            state["model"] = json!("chat-model");
            state["verifiedAt"] = json!(1);
            f.setup.save(&state).unwrap();
            atomic(
                &f.setup.config,
                &policy("chat-model", state["item"].as_str().unwrap()).unwrap(),
            )
            .unwrap();
            let (url, task) = server(vec![
                response(json!({"offline":false,"status":"ok"}), ""),
                response(json!({"models":[{"name":"openai","model":"chat-model","endpoint":API,"key_ok":true}],"dry_run":false}), ""),
                response(json!({"choices":[{"message":{"content":"connected"}}]}), "x-wayfinder-router-request-id: expected-receipt\r\n"),
                response(json!({"recent":[{"request_id":receipt,"served_by":"openai","http_status":200,"outcome":"succeeded"}]}), "")
            ]).await;
            f.setup.endpoint = url;
            let result = f.setup.action("test", "", "").await;
            task.await.unwrap();
            assert_eq!(result.is_ok(), receipt == "expected-receipt");
            assert_eq!(
                f.setup.load().unwrap().get("verifiedAt").is_some(),
                receipt == "expected-receipt"
            );
        }
    }
    #[tokio::test]
    async fn provider_errors_are_sanitized_and_redirects_are_not_followed() {
        for code in ["401 Unauthorized", "302 Found"] {
            let f = Fixture::new();
            let body = "sensitive-provider-diagnostic";
            let (url, task) = server(vec![format!("HTTP/1.1 {code}\r\nLocation: http://127.0.0.1:1/secret\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}", body.len())]).await;
            let error = request(&f.setup.client, &url, Some("secret"), None)
                .await
                .unwrap_err();
            task.await.unwrap();
            assert!(!error.contains(body));
        }
    }
    #[test]
    fn rejects_injection_and_invalid_endpoints() {
        assert!(policy("model\"\n", "abcdef0123456789abcdef0123456789").is_err());
        assert!(policy("chat", "$(anything)").is_err());
        let f = Fixture::new();
        for endpoint in [
            "https://example.com",
            "http://127.0.0.1:0",
            "http://127.0.0.1:65536",
            "http://127.0.0.1:80/path",
        ] {
            assert!(Setup::new(f.setup.config.clone(), endpoint.into(), &f.setup.config).is_err());
        }
    }
    #[tokio::test]
    async fn subprocess_output_is_bounded_and_errors_are_sanitized() {
        let f = Fixture::new();
        let program = f.root.join("child");
        executable(&program, "#!/bin/sh\nprintf secret >&2\nexit 1\n");
        assert!(
            !child(&program, &[], &[])
                .await
                .unwrap_err()
                .contains("secret")
        );
        executable(&program, "#!/bin/sh\nhead -c 1048577 /dev/zero\n");
        assert!(child(&program, &[], &[]).await.is_err());
    }
    #[tokio::test]
    async fn verifies_real_gateway_delivery_and_receipt_after_restart() {
        use wayfinder_gateway::delivery::{
            BufferedDelivery, BufferedDeliveryResponse, DeliveryFuture,
        };
        use wayfinder_gateway::{AppState, ConfiguredModel, build_router};
        struct Provider;
        impl BufferedDelivery for Provider {
            fn send<'a>(&'a self, _: &'a ConfiguredModel, _: Value) -> DeliveryFuture<'a> {
                Box::pin(async {
                    Ok(BufferedDeliveryResponse::new(axum::http::StatusCode::OK, "application/json", axum::body::Bytes::from_static(br#"{"choices":[{"message":{"role":"assistant","content":"connected"},"finish_reason":"stop"}],"usage":{"prompt_tokens":8,"completion_tokens":1,"total_tokens":9}}"#)))
                })
            }
        }
        let mut f = Fixture::new();
        let mut state = f.state("test");
        state["model"] = json!("chat-model");
        let source = policy("chat-model", state["item"].as_str().unwrap()).unwrap();
        f.setup.save(&state).unwrap();
        atomic(&f.setup.config, &source).unwrap();
        for _ in 0..2 {
            let routing = wayfinder_config::routing_config_from_toml(
                &source,
                "test",
                None,
                wayfinder_config::TierOrderPolicy::StrictInput,
            )
            .unwrap();
            let gateway = AppState::new(
                routing,
                vec![ConfiguredModel::new(
                    "openai",
                    API,
                    "chat-model",
                    None,
                    true,
                )],
                false,
                "setup-test",
            )
            .with_delivery(std::sync::Arc::new(Provider));
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
            f.setup.endpoint = format!("http://{}", listener.local_addr().unwrap());
            let task = tokio::spawn(async move {
                axum::serve(listener, build_router(gateway)).await.unwrap();
            });
            let result = f.setup.action("test", "", "").await;
            task.abort();
            let _ = task.await;
            assert_eq!(result.unwrap()["stage"], "verified");
        }
    }
    #[tokio::test]
    async fn locks_serialize_mutations_and_release_after_cancellation() {
        let f = Fixture::new();
        let lock = acquire_lock(&f.setup.directory).unwrap();
        assert!(acquire_lock(&f.setup.directory).is_err());
        drop(lock);
        assert!(acquire_lock(&f.setup.directory).is_ok());
        fs::remove_file(f.setup.directory.join("lock")).unwrap();
        symlink(&f.setup.config, f.setup.directory.join("lock")).unwrap();
        assert!(acquire_lock(&f.setup.directory).is_err());
        assert_eq!(read(&f.setup.config).unwrap(), STARTER);
    }
    #[tokio::test]
    async fn cancelling_subprocess_kills_its_process_group() {
        let f = Fixture::new();
        let program = f.root.join("slow");
        let marker = f.root.join("survived");
        executable(
            &program,
            &format!(
                "#!/bin/sh\n(sleep 0.3; touch '{}') &\nwait\n",
                marker.display()
            ),
        );
        assert!(
            tokio::time::timeout(Duration::from_millis(100), child(&program, &[], &[]))
                .await
                .is_err()
        );
        tokio::time::sleep(Duration::from_millis(400)).await;
        assert!(!marker.exists());
    }
}
