{{- if and .Values.redis.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wayfinder-router.redisName" . }}
  labels:
    {{- include "wayfinder-router.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wayfinder-router.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "wayfinder-router.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.redis.port }}
  egress: []
{{- end }}
